import React from "react";

export default function Head() {
  return (
    <>
      <link rel="icon" href="/favicon.ico" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta name="description" content="Generated by create next app & Tailwind CSS" />
      <meta name="og:title" content="Next.js + Tailwind CSS Blog App" />
      <title>⚡blog.app</title>
    </>
  );
}
