import React from "react";

export default function Head() {
  return (
    <>
      <link rel="icon" href="/favicon.ico" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta name="description" content="Generated by create next app & Tailwind CSS" />
      <meta name="og:title" content="Next.js + Tailwind CSS Blog App" />
      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:site" content="@app" />
      <meta name="twitter:creator" content="@app" />
      <meta name="twitter:title" content="Next.js + Tailwind CSS Blog App" />
      <meta name="twitter:description" content="Generated by create next app & Tailwind CSS" />
      <meta property="og:url" content="https://nextwind-blog.vercel.app/" />
      <meta property="og:title" content="Next.js + Tailwind CSS Blog App" />
      <meta property="og:description" content="Generated by create next app & Tailwind CSS" />
      <title>⚡blog.app</title>
    </>
  );
}
